### ISSUE TITLE
don't redirect to http from https if SECURE_SSL_REDIRECT is False

### ISSUE THREAD

**Issue by stefanfoulis** [divio/aldryn-sites#4]
In the case of `SECURE_SSL_REDIRECT=False` (the default) and if the url already is https, aldryn-sites tries to redirect to http. The correct behaviour would be to stay on https.

**Comment by bplociennik** [comment]
Closing, it was fixed in `0.5.4`:

> * Changed to do not redirect from https to http if `SECURE_SSL_REDIRECT` is not
>   explicitly set to `False`
